name: Generate APK (Direct Engine)
on:
  workflow_dispatch:
  push:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install dependencies
        run: npm install

      - name: Prebuild Native Files
        env:
          EAS_NO_VCS: 1
        run: npx expo prebuild --platform android --non-interactive

      - name: Build APK with Gradle
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
          JAVA_OPTS: "-Xmx4096m"
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SmartExpense-APK
          path: android/app/build/outputs/apk/release/app-release.apk
