name: Generate APK
on:
  workflow_dispatch: # Allows manual trigger
  push:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Build APK Locally
        env:
          EAS_NO_VCS: 1
          NODE_OPTIONS: "--max-old-space-size=4096"
          JAVA_OPTS: "-Xmx4096m"
        run: |
          eas build --platform android --profile preview --local --non-interactive --verbose

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SmartExpense-APK
          path: "*.apk"
